### ISSUE TITLE
Problem with umbrella project

### ISSUE THREAD

**Issue by philipgiuliani** [JakeBecker/vscode-elixir-ls#6] opened 2017-06-15 07:19 UTC
Hi, im getting the following error message in my umbrella project which contains 6 sub projects.
```
[Warn  - 9:17:37 AM] Build failed: %RuntimeError{message: "trying to access Mix.Project.app_path for an umbrella project but umbrellas have no app"}
```

```
# mix.exs in the root
def project do
    [apps_path: "apps",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps(),
     version: "1.0.0",
     aliases: aliases()]
  end
```

System: OS X

**Comment by JakeBecker** [comment] 2017-06-15 07:21
Unfortunately, umbrella apps are currently unsupported. Yes, I know this sucks :) I'm working on improving the build process to make it more robust. You might have to wait for updates before ElixirLS works for this.

Thanks for the bug report. I'll report back here when I've fixed it :)

**Comment by DominikGuzei** [comment] 2017-06-22 16:07
@JakeBecker is there any way I could support you with fixing this? I would love to have this working as im building an umbrella project right now 😉

**Comment by webdeb** [comment] 2017-10-21 15:00
Now I understand why its not working in my project.
Should be mentioned in the Readme IMHO. 

Anyway I'll give it a try on some other (non-umbrella) project, this looks very promisingly.

**Comment by JakeBecker** [comment] 2017-10-21 18:04
@webdeb Sorry, I forgot to update this issue because it's a duplicate of one on https://github.com/JakeBecker/elixir-ls

The latest release of the plugin supports this, but you'll need to update Elixir to 1.6 to see build diagnostics in the editor. Please read this for more info: https://medium.com/@JakeBeckerCode/elixirls-0-2-better-builds-code-formatter-and-incremental-dialyzer-be70999ea3e7

Closing this issue. Thanks!

**Closed by JakeBecker** 2017-10-21 18:04 UTC

**Comment by webdeb** [comment] 2017-10-21 22:02
@JakeBecker thank you for your reply.. Btw. I am no elixir-master with kiex. The syntax highlighting is working, docs on hover also, but I was really interested in the debugger support. I've followed the docs, placed the configuration snipped into the configurations array. But when I click on run, but it the tests are not fired, no output.. nothing.. sry, if its the wrong place, I can open a new issue with more information..
