### ISSUE TITLE
Circular Dependency Error

### ISSUE THREAD

**Issue by micahrye** [JakeBecker/vscode-elixir-ls#36] opened 2018-02-03 11:09 UTC
**Issue**
In VSCode I was getting the red squiggly line that indicates an issue. Mouse over the offending line and it pointed to the type of error you get for circular dependencies, here is the error message:
```
[ElixirLS]
an exception was raised:
    ** (Mix.Error) Trying to load Sysfs.Mixfile from "/code/sysfs/mix.exs" but another project with the same name was already defined at "/code/sysfs/mix.exs"
        (mix) lib/mix.ex:291: Mix.raise/1
        (elixir) src/elixir_module.erl:242: anonymous fn/5 in :elixir_module.expand_callback/6
        (elixir) src/elixir_module.erl:241: :elixir_module.expand_callback/6
        (elixir) src/elixir_module.erl:101: :elixir_module.compile/5
        (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
        (elixir) src/elixir.erl:233: :elixir.eval_forms/4
        (elixir) src/elixir_compiler.erl:61: :elixir_compiler.eval_forms/3
        (elixir) src/elixir_lexical.erl:18: :elixir_lexical.run/3
No documentation available
```

The code ran fine, there was no issues. Also, all the previous times I have worked on this project I was not getting the above issue. It was obviously related to `vscode-elixir-ls` because if I disable it there is no problem, plus like I said there was no problem running the code. 

After investigating I found that the issue was caused by VSCode holding an old reference to the project in memory. By fulling closing VSCode and restarting the issue went away. 

Not sure if this is fixable by this project or if this is an issue with VSCode, but I wanted to share it here as this or other "odd" behavior might be fixable with a full restart of VSCode.

Guess VSCode kinda has that old Windows quality of "ctl-alt-delete" fixing things :)

**Comment by JakeBecker** [comment] 2018-03-12 15:57
Can you check whether this is reproducible in the latest release? I fixed some bugs having to do with loading the mixfile and config .exs files incorrectly, so if that was the cause, it may well be fixed. I'll close this if you can no longer reproduce it.

**Comment by JakeBecker** [comment] 2020-04-16 03:52
This project has moved!

It's now being maintained by proactive volunteers from the Elixir community over at [elixir-lsp](https://github.com/elixir-lsp)/[vscode-elixir-ls](https://github.com/elixir-lsp/vscode-elixir-ls). The main ElixirLS codebase is now at [elixir-lsp](https://github.com/elixir-lsp)/[elixir-ls](https://github.com/elixir-lsp/elixir-ls). Updates will continue to be published from that repo to the original VS Code extension, so no need to switch plugins.

To avoid inundating the new maintainers with issues, please verify that your issue persists with the latest version of the extension (which is published from the new repo) before re-filing your issue there.

Thanks for using ElixirLS!

**Closed by JakeBecker** 2020-04-16 03:52 UTC
