### ISSUE TITLE
Error with umbrella project

### ISSUE THREAD

**Issue by nitingupta910** [JakeBecker/vscode-elixir-ls#31] opened 2018-01-18 03:08 UTC
With umbrella project, the plugin is throwing this error:

```
[ElixirLS]
an exception was raised:
    ** (Mix.Config.LoadError) could not load config ../../config/config.exs
    ** (File.Error) could not read file "../../config/config.exs": no such file or directory
        (elixir) lib/file.ex:310: File.read!/1
        (mix) lib/mix/config.ex:189: Mix.Config.read!/2
        (mix) lib/mix/tasks/loadconfig.ex:37: Mix.Tasks.Loadconfig.load/1
        (mix) lib/mix/tasks/loadconfig.ex:27: Mix.Tasks.Loadconfig.run/1
        (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
        (language_server) lib/language_server/build.ex:116: ElixirLS.LanguageServer.Build.reload_project/0
        (language_server) lib/language_server/build.ex:16: anonymous fn/1 in ElixirLS.LanguageServer.Build.build/2
        (stdlib) timer.erl:166: :timer.tc/1
```

The relevant project structure is like:
```
/config
    config.exs
/apps/foo
    mix.exs
```

`/apps/foo/mix.exs` has entry like this: ` config_path: "../../config/config.exs",`

Basically it's an Elixir Phoenix umbrella project: `mix phx.new hello --umbrella`

**Comment by JakeBecker** [comment] 2018-03-08 22:37
I was unable to reproduce this on the latest release, v0.2.16. I've fixed a number of similar failures in the past few releases, so I think it's likely fixed now. Please re-open if it remains a problem.

**Closed by JakeBecker** 2018-03-08 22:37 UTC
