### ISSUE TITLE
Autocompleting annotations inserts another `@` in some situations

### ISSUE THREAD

**Issue by ndac-todoroki** [JakeBecker/vscode-elixir-ls#59] opened 2018-03-18 09:30 UTC
I work in vscode 1.21.1 and elixir-ls 0.2.17
Annotations (`@xxx`) autocompleting is buggy inside braces. 

GIF:
![peek 2018-03-18 18-24](https://user-images.githubusercontent.com/11530165/37564470-00db4144-2ada-11e8-8d46-76c9e0e4eb11.gif)

**Comment by JakeBecker** [comment] 2018-03-18 14:39
This is a dupe of https://github.com/JakeBecker/elixir-ls/issues/66 and is fixed in master, but I haven't done a release with the fix yet. I'll leave this issue open until I do.

**Comment by ndac-todoroki** [comment] 2018-03-18 14:58
Oh, sorry I haven't searched in that repo! :)

**Comment by JakeBecker** [comment] 2018-03-19 20:07
Just published v0.2.19 with the fix.

**Closed by JakeBecker** 2018-03-19 20:07 UTC
